### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by CodingGorilla** [jokokko/serilog-sinks-marten#1]
Just curious what the status of this project is, I'm considering it for a project but it looks like it's not being actively maintained.

**Comment by jokokko** [comment]
Hello.

Is there something not implemented? Something buggy, something missing? I certainly hope to contribute to maintenance, while recognizing that logging infrastructure is an area with hopefully minimal churn.

Thanks for feedback. Always appreciated.

**Comment by CodingGorilla** [comment]
@jokokko I haven't tried it yet, I just noticed that it was still a pre-release package and hasn't been updated in 8 months.  We have policies about using pre-release packages so I wouldn't be able to use it at this point.

**Comment by jokokko** [comment]
v.1.0.0 NuGet listed, i.e. non-pre-release.
