### ISSUE TITLE
No Logs in Postgres

### ISSUE THREAD

**Issue by thedumbtechguy** [jokokko/serilog-sinks-marten#2]
I have this configuration in an Asp Net Core 2.1 app

```
var martenStore = DocumentStore.For(o =>
                {
                    o.Connection(hostingContext.Configuration.GetSection("ConnectionString").GetValue<string>("Marten"));
                    o.DatabaseSchemaName = "marten";

                    o.AutoCreateSchemaObjects = AutoCreate.All;
                });

                // Configure serilog pipelines
                Log.Logger = new LoggerConfiguration()
                            .MinimumLevel.Debug()
                            .Enrich.FromLogContext()
                            .ReadFrom.Configuration(hostingContext.Configuration)
                            .WriteTo.Marten(
                                martenStore,
                                c =>
                                {
                                    c.UseTenancy("logs");
                                    //c.UseEventStore(e => e.Level == LogEventLevel.Error ? "error" : "other");
                                },
                                batchSizeLimit: 50,
                                period: TimeSpan.FromSeconds(2),
                                restrictedToMinimumLevel: LogEventLevel.Debug)
                            .CreateLogger();
```

Can't get any logs to appear

**Comment by jokokko** [comment]
Hmm, checking with Serilog self-logging might help to see what is going on: https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

But I'll check if it's a sink related problem once I'm off the road.

**Comment by jokokko** [comment]
Thanks for reporting this. Fixed it (v.1.0.0, NuGet validating) by accommodating a breaking change in Marten bulk insertion API in the version 2.x line.

**Comment by thedumbtechguy** [comment]
Awesome. Just got my machine back today. Glad you fixed it.

**Comment by thedumbtechguy** [comment]
Sorry to bump this, but I want to be sure if there's a bug before I create another issue.

I used
```
c.UseTenancy("logs");
c.UseEventStore(e => e.Level.ToString());
```

and the effect was no different from when I didn't do any configuration.
Is this normal? Should I open a proper issue?

![image](https://user-images.githubusercontent.com/923493/45178318-3814b400-b20d-11e8-858f-8b1a8d7f4ce4.png)

**Comment by jokokko** [comment]
@thedumbtechguy When using the Marten event store, the log entries will be in the `mt_events` table (this is Marten convention).

E.g. `c.UseEventStore(e => $"errors-{e.Timestamp.Date.ToShortDateString()}");`

![image](https://user-images.githubusercontent.com/1404295/45199819-59f65100-b276-11e8-9935-ad6a6470df97.png)
